### PR TITLE
Add int64 support

### PR DESCRIPTION
**Pull request by gunslinger23**
## Changed

1. Add Object & Array 64-bit int support (Set/Get/Push to array)
2. Fix warnings of type conversion
3. Update testing plugin

> Already test in game! 👌

### CODE REVIEW

**Comment by gunslinger23** [comment]
ripext-test

**Comment by ErikMinekus** [comment]
Thanks! Can you add `JSONArray.PushInt64` as well?

**Comment by gunslinger23** [comment]
> Thanks! Can you add `JSONArray.PushInt64()` as well?

Sure, I almost forgot it 😂

**Comment by gunslinger23** [comment]
Testing POST Response:
```json
{
    "args": {},
    "data": "{\"id\": 1, \"int64\": 9223372036854775800, \"jsonrpc\": 2.0, \"bool\": true, \"method\": \"subtract\", \"null\": null, \"params\": [{\"id\": 1}, 1, 9223372036854775800, 2.0, true, \"string\", null]}",
    "files": {},
    "form": {},
    "headers": {
        "Accept": "application/json",
        "Accept-Encoding": "deflate, gzip",
        "Content-Type": "application/json",
        "Host": "nghttp2.org",
        "Transfer-Encoding": "chunked"
    },
    "json": {
        "bool": true,
        "id": 1,
        "int64": 9223372036854775800,
        "jsonrpc": 2.0,
        "method": "subtract",
        "null": null,
        "params": [
            {
                "id": 1
            },
            1,
            9223372036854775800,
            2.0,
            true,
            "string",
            null
        ]
    },
    "origin": "",
    "url": "https://nghttp2.org/httpbin/post"
}
```

**Comment by gunslinger23** [comment]
@ErikMinekus It's ready for merge 😉

**Pull request merged**
